version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID    : "554040323477"
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPO_NAME     : "ecr-stock-feed"
    ECR_IMAGE_TAG     : "latest"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Check aws and git version"
      - aws --version
      - git --version

  pre_build:
    commands:
      - echo "Login to AWS ECR and get commit id"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION| docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_ID=$(git rev-parse --short HEAD)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_NAME:$ECR_IMAGE_TAG . || exit 1
      - docker tag $ECR_REPO_NAME:$ECR_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$ECR_IMAGE_TAG
      - docker tag $ECR_REPO_NAME:$ECR_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$COMMIT_ID

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$ECR_IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$COMMIT_ID