version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-feed-app
    depends_on:
      - postgres
      - redis
    environment:
      DB_URL: stock-feed-postgres:5432/stock_feed_db
      REDIS_HOST: stock-feed-redis
      DB_USERNAME: root
      DB_PASSWORD: root
      GEN_ENABLE: true
      CACHEABLE: true
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    container_name: stock-feed-postgres
    environment:
      POSTGRES_DB: stock_feed_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: stock-feed-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  postgres_data: