spring:

  application:
    name: stocksfeed

  r2dbc:
    url: r2dbc:pool:postgresql://${DB_URL:localhost:5432/stock_feed_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  flyway:
    url: jdbc:postgresql://${DB_URL:localhost:5432/stock_feed_db}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

rate-limiter:
  rate: 3
  timeline: 5000 # 5 * 1000ms
  timeout: 100

quote-generation:
  enabled: ${GEN_ENABLE:true}
  delay: ${GEN_DELAY:60000} # 60 * 1000ms = 1 min

redis-cache:
  host: ${REDIS_HOST:localhost}
  enabled: ${CACHEABLE:true}

company:
  load: true
  init-path: classpath:companies.csv


logging:
  level:
    org:
      springframework:
        security: DEBUG
        data:
          r2dbc: DEBUG