spring:

  application:
    name: stocksfeed

  r2dbc:
    url: r2dbc:pool:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:stock_feed_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:stock_feed_db}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}


management:
  endpoint:
    health:
      group:
        liveness:
          additional-path: server:/liveness
        readiness:
          additional-path: server:/readiness

rate-limiter:
  rate: 3
  timeline: 5000 # 5 * 1000ms

quote-generation:
  enabled: ${GEN_ENABLE:true}
  delay: ${GEN_DELAY:30000} # 30 * 1000ms

redis-cache:
  enabled: ${CACHEABLE:true}
  host: ${REDIS_HOST:localhost}

company:
  load: true
  init-path: classpath:companies.csv


logging:
  level:
    org:
      springframework:
        security: DEBUG
        data:
          r2dbc: DEBUG