spring:

  r2dbc:
    url: r2dbc:pool:postgresql://${DB_URL:localhost:5432/stock_feed_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  flyway:
    url: jdbc:postgresql://${DB_URL:localhost:5432/stock_feed_db}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

jquants:
  mail_address: ${MAIL_ADDRESS:igor.balabay01@gmail.com}
  password: ${PASSWORD:Bala4496Bala4496}

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG