spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/stock_feed_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/stock_feed_db
    user: root
    password: root

#redis:
#  host: localhost
#  port: 6379

jquants:
  mail_address: igor.balabay01@gmail.com
  password: Bala4496Bala4496

logging:
  level:
    org:
      hibernate: INFO