spring:

  application:
    name: stocksfeed

  r2dbc:
    url: r2dbc:pool:postgresql://${DB_URL:localhost:5432/stock_feed_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  flyway:
    url: jdbc:postgresql://${DB_URL:localhost:5432/stock_feed_db}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

rate-limiter:
  rate: 10
  timeline: 10

quote-generation:
  enabled: ${GEN_ENABLE:false}
  delay: ${GEN_DELAY:60000} # 60 * 1000ms = 1 min

redis-cache:
  enabled: ${CACHEABLE:false}

company:
  init-path: classpath:companies.csv


logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG