apiVersion: v1
kind: Namespace
metadata:
  name: stock-feed-namespace

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-microservice
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
#    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:your-region:your-account:certificate/your-cert-id"
#    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  selector:
    app: stock-feed-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: stock-feed-microservice
spec:
  selector:
    app: stock-feed-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-feed-deployment
  labels:
    app: stock-feed-service
  namespace: stock-feed-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-feed-service
  template:
    metadata:
      labels:
        app: stock-feed-service
    spec:
      containers:
        - name: ecr-stock-feed
          image: 554040323477.dkr.ecr.us-east-1.amazonaws.com/ecr-stock-feed:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "stock-feed-db.c2zo4gtpu4id.us-east-1.rds.amazonaws.com:5432/stock_feed_db"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: GEN_ENABLE
              value: "true"
            - name: CACHEABLE
              value: "true"
            - name: REDIS_HOST
              value: "stock-feed-redis.sqxw2k.clustercfg.use1.cache.amazonaws.com:6379"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /stock-feed-service/health-status
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10

#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: stock-feed-service-nodeport
#  labels:
#    app: stock-feed-service
#  namespace: stock-feed-namespace
#spec:
#  type: NodePort
#  selector:
#    app: stock-feed-service
#  ports:
#    - port: 8080
#      targetPort: 8080
#      nodePort: 32123

#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres
#spec:
#  type: ExternalName
#  externalName: postgresdb.c2zo4gtpu4id.us-east-1.rds.amazonaws.com