apiVersion: v1
kind: Namespace
metadata:
  name: stock-feed-namespace

---

apiVersion: v1
kind: Service
metadata:
  name: stock-feed-service
spec:
  selector:
    app: stock-feed-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-feed-deployment
  labels:
    app: stock-feed-app
  namespace: stock-feed-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-feed
  template:
    metadata:
      labels:
        app: stock-feed
    spec:
      containers:
        - name: stock-feed-api
          image: 554040323477.dkr.ecr.us-east-1.amazonaws.com/ecr-stock-feed:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "stock-feed-db.c2zo4gtpu4id.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "stock_feed_db"
            - name: REDIS_HOST
              value: "stock-feed-redis.sqxw2k.clustercfg.use1.cache.amazonaws.com:6379"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: GEN_ENABLE
              value: "true"
            - name: CACHEABLE
              value: "true"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /stock-feed-app/health-status
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10

#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: stock-feed-service-nodeport
#  labels:
#    app: stock-feed-app
#  namespace: stock-feed-namespace
#spec:
#  type: NodePort
#  selector:
#    app: stock-feed-app
#  ports:
#    - port: 8080
#      targetPort: 8080
#      nodePort: 32123

#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres
#spec:
#  type: ExternalName
#  externalName: stock-feed-db.c2zo4gtpu4id.us-east-1.rds.amazonaws.com