name: Java Spring Boot CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Test with Maven
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: [ build, test ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Log in to AWS ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 554040323477.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag Docker image for AWS ECR
        run: |
          docker tag ecr-stock-feed:latest 554040323477.dkr.ecr.us-east-1.amazonaws.com/ecr-stock-feed:${{ steps.commit_sha.outputs.sha }}
          docker tag ecr-stock-feed:latest 554040323477.dkr.ecr.us-east-1.amazonaws.com/ecr-stock-feed:latest

      - name: Push Docker image to AWS ECR
        run: |
          docker push 554040323477.dkr.ecr.us-east-1.amazonaws.com/ecr-stock-feed:${{ steps.commit_sha.outputs.sha }}
          docker push 554040323477.dkr.ecr.us-east-1.amazonaws.com/ecr-stock-feed:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Update kube config
        run: aws eks update-kubeconfig --name eks-stockfeed

      - name: Deploy to EKS
        run: kubectl apply -f manifest/stock-feed-manifest.yaml

